services:
  - type: web
    name: cheaplist-backend
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000
