services:
  - type: web
    name: cheaplist-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip curl gnupg
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      rm -f google-chrome-stable_current_amd64.deb
      pip install -r requirements.txt
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000
