services:
  - type: web
    name: cheaplist-backend
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y \
        chromium \
        chromium-driver \
        fonts-liberation \
        libnss3 \
        libgconf-2-4 \
        libxss1 \
        libappindicator1 \
        libindicator7 \
        wget \
        curl \
        gnupg2 && \
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
